"""empty message

Revision ID: 1db5f1914258
Revises: 
Create Date: 2019-12-24 20:36:25.235260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

# revision identifiers, used by Alembic.
revision = '1db5f1914258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('Users_id_seq')))
    op.create_table('Users',
    sa.Column('id', sa.Integer(), server_default=sa.text('nextval(\'"Users_id_seq"\')'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('polys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.execute(CreateSequence(Sequence('seed_meta_id_seq')))
    op.create_table('seed_meta',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seed_meta_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_meta')
    op.drop_table('Users')
    op.execute('DROP SEQUENCE "seed_meta_id_seq"')
    op.execute('DROP SEQUENCE "Users_id_seq"')
    # ### end Alembic commands ###
