"""empty message

Revision ID: f12de8a0ea26
Revises: 1db5f1914258
Create Date: 2019-12-25 13:27:02.016876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f12de8a0ea26'
down_revision = '1db5f1914258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('GeoJSONs_id_seq')))
    op.create_table('GeoJSONs',
    sa.Column('id', sa.Integer(), server_default=sa.text('nextval(\'"GeoJSONs_id_seq"\')'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GeoJSONs')
    op.execute('DROP SEQUENCE "GeoJSONs_id_seq"')
    # ### end Alembic commands ###
